import Head from "next/head";

import { AppContext } from "/src/components/AppState.js";
import { useContext } from "react";

import Header from "/src/components/Header";
import Footer from "/src/components/Footer";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🐝</text></svg>"
        />
      </Head>

      <Header />

      <div className="container mx-auto">
        <div className="flex h-screen items-center justify-center">
          <div className="max-w-sm rounded-md p-8 shadow-md outline">
            <h1 className="text-base">Active Subleases</h1>
            <p className="mt-2 text-sm text-gray-500">
              It looks like you don't have any subleases at the moment.
            </p>
            <button className="mt-3 rounded-md px-2 py-1 text-xs outline outline-1 outline-yellow-400 text-white bg-yellow-600 hover:bg-yellow-500">
              Create a sublease
            </button>
          </div>
        </div>
      </div>

      <main className="bg-gray-500">
        <Footer />
      </main>
    </>
  );
}
