import Head from "next/head";

import { AppContext } from "/src/components/AppState.js";
import { useContext } from "react";

import Header from "/src/components/Header";
import Footer from "/src/components/Footer";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" />
         */}
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🐝</text></svg>"
        />
      </Head>

      <Header />
      <main className="bg-gray-500">
        <Footer />
      </main>
    </>
  );
}
